# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UroCommand.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10UroCommand.proto\x12\x10uropatruljen_app\"\x89\x02\n\x07\x43ommand\x12\x14\n\x07\x63ommand\x18\x01 \x01(\tH\x01\x88\x01\x01\x12*\n\x06\x63lient\x18\x02 \x01(\x0b\x32\x18.uropatruljen_app.ClientH\x00\x12(\n\x05music\x18\x03 \x01(\x0b\x32\x17.uropatruljen_app.MusicH\x00\x12(\n\x05light\x18\x04 \x01(\x0b\x32\x17.uropatruljen_app.LightH\x00\x12$\n\x03uro\x18\x05 \x01(\x0b\x32\x15.uropatruljen_app.UroH\x00\x12/\n\x07network\x18\x06 \x01(\x0b\x32\x1c.uropatruljen_app.NetworkCreH\x00\x42\x05\n\x03msgB\n\n\x08_command\"B\n\x06\x43lient\x12\x12\n\x05token\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04imei\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_tokenB\x07\n\x05_imei\"=\n\x05Music\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05title\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x08\n\x06_title\"y\n\x05Light\x12\x12\n\x05state\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x10\n\x03red\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x12\n\x05green\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x11\n\x04\x62lue\x18\x04 \x01(\x05H\x03\x88\x01\x01\x42\x08\n\x06_stateB\x06\n\x04_redB\x08\n\x06_greenB\x07\n\x05_blue\"#\n\x03Uro\x12\x12\n\x05model\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_model\"D\n\nNetworkCre\x12\x11\n\x04ssid\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04pass\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_ssidB\x07\n\x05_passB5\n%com.example.uropatruljen_app.protobufB\nUroCommandP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UroCommand_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.example.uropatruljen_app.protobufB\nUroCommandP\001'
  _COMMAND._serialized_start=39
  _COMMAND._serialized_end=304
  _CLIENT._serialized_start=306
  _CLIENT._serialized_end=372
  _MUSIC._serialized_start=374
  _MUSIC._serialized_end=435
  _LIGHT._serialized_start=437
  _LIGHT._serialized_end=558
  _URO._serialized_start=560
  _URO._serialized_end=595
  _NETWORKCRE._serialized_start=597
  _NETWORKCRE._serialized_end=665
# @@protoc_insertion_point(module_scope)
